### ISSUE TITLE
Fully-trained models?

### ISSUE THREAD

**Issue by sergeyf** [webis-de/set-encoder#3]
Hello,

Where can the fully-trained 330M model be downloaded?

Also, if I wanted to train a larger model using your pipeline - is that currently supported in the code?

**Comment by fschlatt** [comment]
Hey!

I haven't gotten around to uploading the already fine-tuned models. I promise to do so by the end of the week ;)
A fine-tuned [monoELECTRA model](https://huggingface.co/webis/monoelectra-large) is already uploaded, but unfortunately, how to use it is unfortunately at the moment also not well documented. I will try to document everyone ASAP.

Fine-tuning larger models should be doable, but currently only encoder-only bert-based backbones (bert, electra, and roberta) are supported. I'm not aware of any larger models

**Comment by sergeyf** [comment]
Thanks!

**Comment by fschlatt** [comment]
I've uploaded the models and added a bit of info in the README. More detailed documentation will follow in the lightning-ir repository within the next few days

**Comment by sergeyf** [comment]
Wonderful, thanks!
